# Generated by Django 4.1.3 on 2022-11-29 03:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('69f9963e-896d-4a16-b56f-076264b66eb7'), editable=False, primary_key=True, serialize=False),
        ),
    ]
