# Generated by Django 4.1.3 on 2022-11-28 18:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeTransaction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('operacao', models.CharField(choices=[('DEBITO', 'Debito'), ('BOLETO', 'Boleto'), ('FINANCIAMENTE', 'Financiamento'), ('CREDITO', 'Credito'), ('RECEBIMENTO_EMPRESTIMO', 'Recebimento Emprestimo'), (
                    'VENDAS', 'Vendas'), ('RECEBIMENTO_TED', 'Recebimento Ted'), ('RECEBIMENTO_DOC', 'Recebimento Doc'), ('OTHER', 'Other')], default='OTHER', max_length=24)),
                ('natureza', models.CharField(max_length=24)),
            ],
        ), migrations.RunSQL("INSERT INTO reader_cnab_typetransaction VALUES(1, 'DEBITO', 'ENTRADA'),(2, 'BOLETO', 'SAIDA'),(3, 'FINANCIAMENTE', 'SAIDA'),(4, 'CREDITO', 'ENTRADA'),(5, 'RECEBIMENTO_EMPRESTIMO', 'ENTRADA'),(6, 'VENDAS', 'ENTRADA'),(7, 'RECEBIMENTO_TED', 'ENTRADA'),(8, 'RECEBIMENTO_DOC', 'ENTRADA'),(9,'ALUGUEL','SAIDA')"),
        migrations.CreateModel(
            name='DataCnab',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('data', models.CharField(max_length=12)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cpf', models.CharField(max_length=11)),
                ('cartao', models.CharField(max_length=12)),
                ('hora', models.CharField(max_length=12)),
                ('nome_representante', models.CharField(max_length=14)),
                ('nome_fantasia', models.CharField(max_length=19)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='tipo_id', to='reader_cnab.typetransaction')),
            ],
        ),
    ]
